### ISSUE TITLE
Questions about usage of SIOP and RP

### ISSUE THREAD

**Issue by kg0r0** [decentralized-identity/did-siop#17]
I'm interested in this project.
I tried to make SIOP and RP work.
But, I don't know how to use, so I couldn't verify DID Authn SIOP request.
Could you write a usage document?

**Comment by awoie** [comment]
Are you referring to the reference implementation? That is still work in progress. We are still about to finalize the last issue in the spec.

**Comment by kg0r0** [comment]
Yes, I'm referring to the reference implementation.

> That is still work in progress. 

Noted with thanks.

**Comment by awoie** [comment]
@kg0r0 we are happy to see more PRs. If you are a DIF member or individual contributor, we would love to see progress in this area.
