### ISSUE TITLE
Split reference implementation folder

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/did-siop#18]
Break down the folder structure into:

- doc
- impl
+- lib
+- demo
---+--- rp
---+--- siop

The lib folder should contain a TypeScript library to create DID SIOP requests and create DID SIOP responses. 

rp folder should contain a demo RP based on the library. The RP should be a Node web application serving a simple login page.

siop folder should contain one or more demos for SIOP DID wallets based on the library. The SIOP DID should be either a terminal app, mobile wallet, browser-wallet or whatever people feel makes sense.

@iamtxena feel free to take a first stab!

**Comment by iamtxena** [comment]
Thanks for the info. I'll start right away. Thanks!
