### ISSUE TITLE
Support response_mode=query

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/did-siop#20]
The OAuth 2.0 Form Post Response Mode requires the OP to send a response via POST into the context of the user agent session where the request began (e.g., back in the system browser context).

For a mobile wallet application, it can be challenging to perform a POST into the system browser context *without* requiring the OP (a SIOP!) to host a web domain that can be loaded in the user agent to perform the POST. Is there a reason not to allow `response_mode=query`?

(While `fragment` avoids the issue of needing to perform a `POST`, it's unsuitable for relying parties that don't require id_token in the front-end, or relying parties that want to avoid running javascript on the front-end, or want to avoid exposing the id_token to third party scripts.)

If there are robust cross-platform techniques for accomplishing a form post via native-app-to-system-browser handoff, that'd also work (maybe a clever use of `data:` URLs)?

**Comment by awoie** [comment]
The reason to not allow `query` was that IMO `query` cannot be used if the response type was `id_token` and an `id_token` is sent in the response.

More infos here:
https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#id_token

Would you agree with this?

**Comment by awoie** [comment]
@jmandel It seems that `fragment` is the only feasible option?

**Comment by jmandel** [comment]
Thanks for the pointer to OIDC definitions. I don't think the analysis there applies when an id_token is being *encrypted*, so I'm not sure we should rule out the possibility of allowing `query` in our specification -- at least, if we can't figure out a practical way to implement `form_post`. 

Re: data URLs, I just meant that the entire contents of a page like the HTML example from https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html#FormPostResponseExample could potentially be b64 encoded and packed into a data URL, which the wallet can open in the systems browser -- but for security reasons I don't think mobile platforms allow redirections to URLs like this. (I haven't actually tried it; I was hoping to learn if anyone has experience with this.)

**Comment by awoie** [comment]
What we can do:
- allow `query` if JWE is being used -> @jmandel, could you pls update the PR #28 . The problem though is security with incorrect implementations. We already saw two independent demos and both demos didn't implement encryption. The chances are high that people would use `query` without JWE.
- create a separate issue for `form_post` with data URLs. Do you think that makes sense?

**Comment by selfissued** [comment]
The reasons that the response_mode=query MUST NOT be used for response_type=id_token are described in https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Security.

**Comment by jmandel** [comment]
This reference is helpful but can you comment on the case where the id_token is encrypted? That case would seem analogous to the example given in your sighted reference for a confidential client: without the appropriate secret (here: decryption key) the value is unusable by third parties.

I may be missing something here so I would appreciate any additional considerations you can share.

**Comment by awoie** [comment]
@selfissued @jmandel can you give an update on the `response_mode=query` option in case encryption was used?

**Comment by jmandel** [comment]
From my perspective, I'm still hoping to understand more about rationale. The reasons explained in the link from @selfissued are clear, but I'm not seeing how they apply in this case.
