### ISSUE TITLE
Provide a way for the relying party to signal that the flow can end in the SIOP

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/did-siop#21]
In some use cases, like conventional "single sign-on", it's important to make sure the user ends up at the relying party's site. This is common and good.

There are other use cases where the RP just wants a set of data (e.g., a DID or some VCs) to be posted to their backend, and the user flow can end in the SIOP "wallet" app where the user approves sharing.

We should add a request parameter like `response_context=wallet` to allow the RP to indicate that it's happy to receive a "blind" submission of the SIOP response, and leave the user flow to terminate within the SIOP.

**Comment by awoie** [comment]
Agree and the https://github.com/decentralized-identity/did-siop/pull/27 looks good.
