### ISSUE TITLE
Inconsistency between "date" and  "in seconds"

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/did-siop#22]
from @jmandel 
> Inconsistency between "date" and  "in seconds" -- also unclear what happens to this across multiple (repeated) polling requests. Should the client iteratively decrement, if it's a count (in seconds)?

@jmandel Could you please provide a potential solution and create a PR to fix this.

**Comment by jmandel** [comment]
I'm going to ask @csuwildcat to help on this -- offline we had discussed *not* adding a separate flow for cross-device access and just adding security considerations. But now I see the additional flow description has been merged, so I want to make sure we're all on the same page.

**Comment by awoie** [comment]
@jmandel yes, it got merged but if this is not required anymore, please create a PR.

**Comment by awoie** [comment]
It seems by merging https://github.com/decentralized-identity/did-siop/pull/26, this issue will be fixed.
