### ISSUE TITLE
Comparison with VC-AuthN-OIDC

### ISSUE THREAD

**Issue by domwoe** [decentralized-identity/did-siop#34]
Is anybody aware of a comparison with the following approach? 
https://github.com/bcgov/vc-authn-oidc

**Comment by awoie** [comment]
we have discussed this in detail in the wg-auth slack channel. 

vc-authn-oidc:
- compatible with OIDC code, implicit, ... flows
- requires centralized OP
- RP requires knowledge of OP
- does not use DID keys for id_token
- relies on popular OIDC flows (e.g., code), thus easier to integrate
- no dedicated OIDC profile required

DID SIOP:
- compatible with OIDC SIOP flow
- no centralized OP required, the wallet is the (SI)OP
- RP does not require knowledge of OP
- does use DID keys for id_token
- relies on less popular SIOP flow, thus a bit more difficult to integrate
- dedicated OIDC profile in case DID/VC capabilities are used

Both are legitimate and address different use cases.
