### ISSUE TITLE
Clarify that DID SIOP is a flavor of DID AuthN

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/did-siop#4]
The way the text in the spec abstract is worded (https://github.com/decentralized-identity/did-siop/blob/master/docs/index.html#L98), it makes it seem like DID AuthN might be some other type of defined construct, format, or framework. We probably want to add more to this to clarify that DID AuthN is an overarching umbrella, under which sits DID SIOP, DID-based HTTP Signatures, and probably DID Comms.

**Comment by awoie** [comment]
RESOLUTION as per Auth WG call on Dec 19th, 2020: rename “DID AuthN profile for OpenID Connect” to “SIOP DID profile”
