### ISSUE TITLE
rephrasing client_id claim to redirect_uri

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/did-siop#46]
This is probably a mere syntax issue: 3.1.1. Request (Regular-device Flow) of did-siop profile states that “client_id MUST specify the **callback URL** of the RP (as per [OIDC.Core])”. But per OIDC.Core 7.2 Self-Issued OpenID Provider Registration, client_id has to be **redirect_uri** value of the Client.

**Comment by awoie** [comment]
Good find. Can you provide a PR that fixes the language.

**Comment by awoie** [comment]
I'm working on a PR that fixes a couple of minor things and I will include this as well.
